apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: research4150.azurecr.io/user-service:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: sqlite-storage
          mountPath: /usr/src/app/db-data/user-service.db
          subPath: user-service.db
      volumes:
      - name: sqlite-storage
        persistentVolumeClaim:
          claimName: user-service-pvc
