name: CI/CD Pipeline

on:
  # Trigger the workflow on push to the develop branch
  push:
    branches:
      - '**'
  # Trigger the workflow on pull requests targeting the develop branch
  pull_request:
    branches:
      - '**'

jobs:
  # Build Docker images for each service
  build-order-service:
    name: Build Order Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t order-service ./services/order-service

      - name: Tag Docker Image
        run: docker tag order-service research4150.azurecr.io/order-service:latest

      - name: Login to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login research4150.azurecr.io -u research4150 --password-stdin

      - name: Push Docker Image to ACR
        run: docker push research4150.azurecr.io/order-service:latest

  build-product-service:
    name: Build Product Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t product-service ./services/product-service

      - name: Tag Docker Image
        run: docker tag product-service research4150.azurecr.io/product-service:latest

      - name: Login to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login research4150.azurecr.io -u research4150 --password-stdin

      - name: Push Docker Image to ACR
        run: docker push research4150.azurecr.io/product-service:latest

  build-user-service:
    name: Build User Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t user-service ./services/user-service

      - name: Tag Docker Image
        run: docker tag user-service research4150.azurecr.io/user-service:latest

      - name: Login to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login research4150.azurecr.io -u research4150 --password-stdin

      - name: Push Docker Image to ACR
        run: docker push research4150.azurecr.io/user-service:latest

  # Run unit and integration tests for each service
  test-order-service:
    name: Test Order Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: |
          cd ./services/order-service
          pnpm install

      - name: Run Tests
        run: |
          cd ./services/order-service
          pnpm jest --testPathPattern=__tests__

  test-product-service:
    name: Test Product Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: |
          cd ./services/product-service
          pnpm install

      - name: Run Tests
        run: |
          cd ./services/product-service
          pnpm jest --testPathPattern=__tests__

  test-user-service:
    name: Test User Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: |
          cd ./services/user-service
          pnpm install

      - name: Run Tests
        run: |
          cd ./services/user-service
          pnpm jest --testPathPattern=__tests__

  # Deploy services to Kubernetes
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: [build-order-service, build-product-service, build-user-service, test-order-service, test-product-service, test-user-service]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Authenticate with Azure
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up AKS credentials
        run: az aks get-credentials --resource-group aks-research-cluster_group --name aks-research-cluster

      - name: Deploy Services
        run: |
          kubectl apply -f k8s/persistent-volumes/user-service-pvc.yml
          kubectl apply -f k8s/persistent-volumes/product-service-pvc.yml
          kubectl apply -f k8s/persistent-volumes/order-service-pvc.yml
          kubectl apply -f k8s/deployments/user-service-deployment.yml
          kubectl apply -f k8s/deployments/product-service-deployment.yml
          kubectl apply -f k8s/deployments/order-service-deployment.yml
          kubectl apply -f k8s/services/user-service-service.yml
          kubectl apply -f k8s/services/product-service-service.yml
          kubectl apply -f k8s/services/order-service-service.yml
          kubectl apply -f k8s/ingress.yml
    
  # Run centralized E2E tests
  test-e2e:
    name: Run End-to-End Tests
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run E2E Tests
        run: pnpm jest tests/e2e/ --verbose
        env:
          BASE_URL: http://4.227.46.180 # change to ingress
